# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/krek07/Documents/PUF/src/xdc/pin.xdc

# XDC: /home/krek07/Documents/PUF/src/xdc/area_2.xdc

# XDC: /home/krek07/Documents/PUF/src/xdc/debug.xdc

# Block Designs: /home/krek07/Documents/PUF/BD/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: /home/krek07/Documents/PUF/BD/system/ip/system_microblaze_0_0/system_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_0 || ORIG_REF_NAME==system_microblaze_0_0} -quiet] -quiet

# IP: /home/krek07/Documents/PUF/BD/system/ip/system_dlmb_v10_0/system_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dlmb_v10_0 || ORIG_REF_NAME==system_dlmb_v10_0} -quiet] -quiet

# IP: /home/krek07/Documents/PUF/BD/system/ip/system_ilmb_v10_0/system_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ilmb_v10_0 || ORIG_REF_NAME==system_ilmb_v10_0} -quiet] -quiet

# IP: /home/krek07/Documents/PUF/BD/system/ip/system_dlmb_bram_if_cntlr_0/system_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==system_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: /home/krek07/Documents/PUF/BD/system/ip/system_ilmb_bram_if_cntlr_0/system_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==system_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: /home/krek07/Documents/PUF/BD/system/ip/system_lmb_bram_0/system_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_0 || ORIG_REF_NAME==system_lmb_bram_0} -quiet] -quiet

# IP: /home/krek07/Documents/PUF/BD/system/ip/system_microblaze_0_axi_periph_0/system_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_periph_0 || ORIG_REF_NAME==system_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: /home/krek07/Documents/PUF/BD/system/ip/system_mdm_1_0/system_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mdm_1_0 || ORIG_REF_NAME==system_mdm_1_0} -quiet] -quiet

# IP: /home/krek07/Documents/PUF/BD/system/ip/system_clk_wiz_1_0/system_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_1_0 || ORIG_REF_NAME==system_clk_wiz_1_0} -quiet] -quiet

# IP: /home/krek07/Documents/PUF/BD/system/ip/system_rst_clk_wiz_1_100M_0/system_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==system_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: /home/krek07/Documents/PUF/BD/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0} -quiet] -quiet

# IP: /home/krek07/Documents/PUF/BD/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: /home/krek07/Documents/PUF/BD/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uartlite_0_0 || ORIG_REF_NAME==system_axi_uartlite_0_0} -quiet] -quiet

# IP: /home/krek07/Documents/PUF/BD/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0} -quiet] -quiet

# IP: /home/krek07/Documents/PUF/BD/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_0 || ORIG_REF_NAME==system_axi_gpio_1_0} -quiet] -quiet

# IP: /home/krek07/Documents/PUF/BD/system/ip/system_arbiter_puf_0_0/system_arbiter_puf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_arbiter_puf_0_0 || ORIG_REF_NAME==system_arbiter_puf_0_0} -quiet] -quiet

# IP: /home/krek07/Documents/PUF/BD/system/ip/system_ila_1_0/system_ila_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ila_1_0 || ORIG_REF_NAME==system_ila_1_0} -quiet] -quiet

# IP: /home/krek07/Documents/PUF/BD/system/ip/system_ila_2_0/system_ila_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ila_2_0 || ORIG_REF_NAME==system_ila_2_0} -quiet] -quiet

# XDC: /home/krek07/Documents/PUF/BD/system/system_ooc.xdc
