set_property SRC_FILE_INFO {cfile:/home/krek07/Documents/PUF/PUF20191/project_1/project_1.srcs/sources_1/xdc/pin.xdc rfile:../../../project_1.srcs/sources_1/xdc/pin.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R2 [get_ports iclk]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R12 [get_ports uart_txd]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports uart_rxd]
